# -- coding: utf-8 --
"""OH-FGS  Project

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1c7vmzYncGBP226UiQpgEo9lBgZeJD1wQ

IMPORT LIBRARIES
"""

# 2. Import libraries
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from xgboost import XGBClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.metrics import classification_report, roc_auc_score
import matplotlib.pyplot as plt
import seaborn as sns
import joblib

# 3. Load dataset (upload your Excel file when prompted)
import streamlit as st
import pandas as pd

uploaded_file = st.file_uploader("Upload OH-FGS Excel file", type=["xlsx"])
if uploaded_file:
    df = pd.read_excel(uploaded_file)
    st.write(df.head())
else:
    st.warning("Please upload an Excel file")

# 4. Feature Selection (One Health Approach)
# Key variables from your dataset + engineered features
one_health_features = [
    # Human Health
    'n_ShInfection',       # Primary target (binary: outbreak if >50)
    'mean_ShEgg',          # Egg burden (continuous)
    'n_female',            # FGS risk group
    'Pop',                 # Population density

    # Environmental
    'LakeYN',              # Lake presence (binary)
    'distance',            # Proximity to water (meters)
    'FloatingVeg',         # Snail habitat indicator
    'Depth',               # Water depth (snail survival)
    'width_shore',         # Shoreline width (transmission zone)

    # Animal/Vector
    'Bulinus',             # Snail vector count
    'Biomph',              # Alternative snail vector
    'circ_score'           # Water body circularity (snail habitat)
]

# Create new features
df['water_contact_risk'] = np.where(df['distance'] < 1000, 1, 0)  # High risk if <1km to water
df['snail_density'] = df['Bulinus'] + df['Biomph']               # Total snail load

# 5. Prepare data
X = df[one_health_features]
y = np.where(df['n_ShInfection'] > 50, 1, 0)  # Binary outbreak target (1 if >50 cases)

# 6. Train/test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.4, random_state=42)

# 7. Train model (Random Forest)
rf_model = RandomForestClassifier(n_estimators=100, class_weight='balanced', random_state=42)
rf_model.fit(X_train, y_train)

dt_model = DecisionTreeClassifier(random_state=42)
dt_model.fit(X_train, y_train)

xg_model = XGBClassifier(random_state=42)
xg_model.fit(X_train, y_train)

lg_model = LogisticRegression(random_state=42)
lg_model.fit(X_train, y_train)

# 8. Evaluate

#Evaluate Random Forest model
y_pred_rf = rf_model.predict(X_test)
print("Random Forest Model Evaluation:")
print(classification_report(y_test, y_pred_rf))
print(f"AUC-ROC: {roc_auc_score(y_test, rf_model.predict_proba(X_test)[:, 1]):.2f}")

# Evaluate Decision Tree model
y_pred_dt = dt_model.predict(X_test)
print("Decision Tree Model Evaluation:")
print(classification_report(y_test, y_pred_dt))
print(f"AUC-ROC: {roc_auc_score(y_test, dt_model.predict_proba(X_test)[:, 1]):.2f}")

# Evaluate XGBoost model
y_pred_xg = xg_model.predict(X_test)
print("\nXGBoost Model Evaluation:")
print(classification_report(y_test, y_pred_xg))
print(f"AUC-ROC: {roc_auc_score(y_test, xg_model.predict_proba(X_test)[:, 1]):.2f}")

# Evaluate Logistic Regression model
y_pred_lg = lg_model.predict(X_test)
print("\nLogistic Regression Model Evaluation:")
print(classification_report(y_test, y_pred_lg))
print(f"AUC-ROC: {roc_auc_score(y_test, lg_model.predict_proba(X_test)[:, 1]):.2f}")

# 9. Feature Importance
plt.figure(figsize=(10, 6))
sns.barplot(x=rf_model.feature_importances_, y=one_health_features)
plt.title("One Health Feature Importance")
plt.show()

import seaborn as sns
df['risk_score'] = lg_model.predict_proba(X)[:, 1]

# Now, the heatmap code should work
# Pivot table: Village x Site risk scores
heatmap_data = df.pivot_table(index='Village', columns='Site',
                             values='risk_score', aggfunc='mean')

# Plot
plt.figure(figsize=(12, 8))
sns.heatmap(heatmap_data, annot=True, cmap="YlOrRd",
            linewidths=0.5, cbar_kws={'label': 'Risk Score'})
plt.title("Schisto Risk by Village and Site")
plt.show()

import pickle

# Save the model
chosen_model = lg_model
with open('schisto_risk_model.pkl', 'wb') as f:
    pickle.dump(chosen_model, f)

print("LGR model saved as schisto_risk_model.pkl")

def send_stakeholder_alerts(village_data, risk_level):
    # Single recipient (modify this to your target email)
    recipient_email = "freitasannie7@gmail.com"

    # Compose the alert message
    message = f"""
    🚨 SCHISTOSOMIASIS ALERT - {village_data['Village']} 🚨
    Risk Level: {risk_level}
    Risk Score: {village_data['risk_score']:.2f}

    📍 Location: Site {village_data['Site']}
    📊 Metrics:
    - Infected Individuals: {village_data['n_ShInfection']}
    - Bulinus Snail Count: {village_data['Bulinus']}
    - Water Contact Risk: {village_data['distance']}m from village

    ⚠ Recommended Actions:
    {generate_intervention_plan(village_data)}

    📅 Next Assessment: {pd.Timestamp.now() + pd.Timedelta(days=7)}
    """

    # Send only one email
    send_email(recipient_email, f"SCHISTO ALERT: {risk_level} Risk Detected", message)

    # Optional: Log the alert (no SMS or emergency protocols)
    print(f"📧 Alert sent to {recipient_email} for {village_data['Village']}")

import pandas as pd
import numpy as np

# Track Intervention Effectiveness
def evaluate_impact(baseline, follow_up):
    improvement = {
        'Risk Reduction': baseline['risk_score'] - follow_up['risk_score'],
        'Case Reduction': (baseline['n_ShInfection'] - follow_up['n_ShInfection'])/baseline['n_ShInfection']*100,
        'Snail Reduction': (baseline['Bulinus'] - follow_up['Bulinus'])/baseline['Bulinus']*100
    }
    return improvement

# Example Report
# Replace 'Diokhor' with an actual Village name from your dataset (e.g., 'Diokhor ')
baseline = df[df['Village']=='Diokhor '].iloc[0]
follow_up = baseline.copy()  # Replace with actual follow-up data
follow_up.update({'risk_score': baseline['risk_score']*0.6,
                 'n_ShInfection': baseline['n_ShInfection']*0.7,
                 'Bulinus': baseline['Bulinus']*0.5})

print("📈 Intervention Effectiveness:")
st.dataframe(pd.DataFrame([evaluate_impact(baseline, follow_up)]))

# -- coding: utf-8 --
import streamlit as st
import pandas as pd
from datetime import datetime

# Set page config - shows immediately
st.set_page_config(
    page_title="OH-FGS Risk Prediction",
    page_icon="🦠",
    layout="wide"
)

# Custom CSS - shows immediately
st.markdown("""
<style>
    .risk-high { background-color: #ffdddd; padding: 15px; border-radius: 10px; }
    .risk-medium { background-color: #fff3cd; padding: 15px; border-radius: 10px; }
    .risk-low { background-color: #d4edda; padding: 15px; border-radius: 10px; }
</style>
""", unsafe_allow_html=True)

# Prediction features - just a list, no loading
PREDICTION_FEATURES = [
    'n_ShInfection', 'mean_ShEgg', 'n_female', 'Pop', 'LakeYN',
    'distance', 'FloatingVeg', 'Depth', 'width_shore', 'Bulinus',
    'Biomph', 'circ_score'
]

# Initialize empty session state - shows immediately
if 'submitted_data' not in st.session_state:
    st.session_state.submitted_data = pd.DataFrame(
        columns=PREDICTION_FEATURES + ['Village', 'Date', 'Risk_Level', 'Risk_Probability']
    )

# Model loader - ONLY called when needed
def get_model():
    """Load model only when first prediction is requested"""
    try:
        import pickle
        with open('schisto_risk_model.pkl', 'rb') as f:
            return pickle.load(f)
    except Exception as e:
        st.error(f"⚠️ Model loading failed: {str(e)}")
        st.info("Please ensure 'schisto_risk_model.pkl' exists in the app directory")
        return None

# Prediction function - calls get_model() only when needed
def predict_risk(input_data):
    """Only loads model when actually making a prediction"""
    model = get_model()
    if not model:
        return None, None
    
    try:
        features = pd.DataFrame([input_data])[PREDICTION_FEATURES]
        proba = model.predict_proba(features)[0][1]
        risk_level = "High" if proba > 0.7 else "Medium" if proba > 0.3 else "Low"
        return risk_level, proba
    except Exception as e:
        st.error(f"Prediction failed: {str(e)}")
        return None, None

# Input form - shows immediately
def show_input_form():
    with st.form("risk_form"):
        st.header("New Risk Assessment")
        
        col1, col2 = st.columns(2)
        
        with col1:
            village = st.text_input("Village Name", "Diokhor")
            date = st.date_input("Assessment Date", datetime.today())
            n_ShInfection = st.number_input("Infected Individuals", min_value=0, value=5)
            mean_ShEgg = st.number_input("Mean Egg Count", min_value=0.0, value=2.5)
            n_female = st.number_input("Female Population", min_value=0, value=15)
            pop = st.number_input("Total Population", min_value=0, value=100)
            
        with col2:
            lake_yn = st.selectbox("Lake Present", ["Yes", "No"])
            distance = st.number_input("Distance to Water (m)", min_value=0, value=500)
            floating_veg = st.selectbox("Floating Vegetation", ["Low", "Medium", "High"])
            depth = st.number_input("Water Depth (m)", min_value=0.0, value=1.2)
            width_shore = st.number_input("Shore Width (m)", min_value=0.0, value=8.0)
            bulinus = st.number_input("Bulinus Snail Count", min_value=0, value=15)
            biomph = st.number_input("Biomph Snail Count", min_value=0, value=3)
            circ_score = st.slider("Water Circularity", 0.0, 1.0, 0.6)
        
        if st.form_submit_button("Calculate Risk"):
            input_data = {
                'Village': village,
                'Date': date.strftime('%Y-%m-%d'),
                'n_ShInfection': n_ShInfection,
                'mean_ShEgg': mean_ShEgg,
                'n_female': n_female,
                'Pop': pop,
                'LakeYN': 1 if lake_yn == "Yes" else 0,
                'distance': distance,
                'FloatingVeg': ["Low", "Medium", "High"].index(floating_veg) + 1,
                'Depth': depth,
                'width_shore': width_shore,
                'Bulinus': bulinus,
                'Biomph': biomph,
                'circ_score': circ_score
            }
            
            risk_level, risk_proba = predict_risk(input_data)
            
            if risk_level:
                # Store results
                input_data.update({
                    'Risk_Level': risk_level,
                    'Risk_Probability': risk_proba
                })
                new_entry = pd.DataFrame([input_data])
                st.session_state.submitted_data = pd.concat(
                    [st.session_state.submitted_data, new_entry],
                    ignore_index=True
                )
                
                # Display results
                risk_class = f"risk-{risk_level.lower()}"
                st.markdown(
                    f'<div class="{risk_class}">'
                    f'<h3>Risk Level: {risk_level}</h3>'
                    f'<p>Probability: {risk_proba:.1%}</p>'
                    f'</div>',
                    unsafe_allow_html=True
                )

# Data viewer - shows immediately
def show_data():
    if not st.session_state.submitted_data.empty:
        st.header("Collected Assessments")
        st.dataframe(st.session_state.submitted_data)
        
        # Export
        csv = st.session_state.submitted_data.to_csv(index=False)
        st.download_button(
            "Export Data as CSV",
            data=csv,
            file_name="schisto_risk_assessments.csv",
            mime="text/csv"
        )
    else:
        st.info("No assessments recorded yet")

# Main app flow
def main():
    st.title("🦠 Schistosomiasis Outbreak Risk Predictor")
    
    tab1, tab2 = st.tabs(["New Assessment", "View Data"])
    
    with tab1:
        show_input_form()
    
    with tab2:
        show_data()

if __name__ == "__main__":
    main()
